export type ThemeColors = {
    primary: string;
    planMode: string;
    selection: string;
    thinking: string;
    success: string;
    error: string;
    info: string;
    background: string;
    surface: string;
    dialogSurface: string;
    thinkingBorder: string;
    dimSeparator: string;
    foreground: string;
    mutedForeground: string;
    selectionForeground: string;
};

export type Theme = {
    name: string;
    colors: ThemeColors;
};

type RawThemeColors = Omit<
    ThemeColors,
    "foreground" | "mutedForeground" | "selectionForeground"
> &
    Partial<
        Pick<ThemeColors, "foreground" | "mutedForeground" | "selectionForeground">
    >;

type RawTheme = {
    name: string;
    colors: RawThemeColors;
};

function getHexChannel(hex: string, start: number) {
    return Number.parseInt(hex.slice(start, start + 2), 16);
}

function isLightColor(hex: string) {
    const normalizedHex = hex.replace("#", "");
    const red = getHexChannel(normalizedHex, 0);
    const green = getHexChannel(normalizedHex, 2);
    const blue = getHexChannel(normalizedHex, 4);
    const brightness = red * 0.299 + green * 0.587 + blue * 0.114;

    return brightness >= 160;
}

function createTheme(theme: RawTheme): Theme {
    const backgroundIsLight = isLightColor(theme.colors.background);
    const selectionIsLight = isLightColor(theme.colors.selection);

    return {
        ...theme,
        colors: {
            ...theme.colors,
            foreground:
                theme.colors.foreground ??
                (backgroundIsLight ? "#1F2328" : "#F5F7FA"),
            mutedForeground:
                theme.colors.mutedForeground ??
                (backgroundIsLight ? "#5F6B7A" : "#9AA4B2"),
            selectionForeground:
                theme.colors.selectionForeground ??
                (selectionIsLight ? "#111827" : "#F8FAFC"),
        },
    };
}

const RAW_THEMES: RawTheme[] = [
    {
        name: "Nightfox",
        colors: {
            primary: "#56D6C2",
            planMode: "#CF8EF4",
            selection: "#89B4FA",
            thinking: "#CF8EF4",
            success: "#82E0AA",
            error: "#E74C5E",
            info: "#56D6C2",
            background: "#0D0D12",
            surface: "#1A1A24",
            dialogSurface: "#0A0A10",
            thinkingBorder: "#34344A",
            dimSeparator: "#4E4E66",
        },
    },
    {
        name: "Catppuccin Mocha",
        colors: {
            primary: "#E0AF68",
            planMode: "#9D7CD8",
            selection: "#B4A4E8",
            thinking: "#9D7CD8",
            success: "#73DACA",
            error: "#F7768E",
            info: "#7AA2F7",
            background: "#11111B",
            surface: "#1E1E2E",
            dialogSurface: "#13131D",
            thinkingBorder: "#45475A",
            dimSeparator: "#585B70",
        },
    },
    {
        name: "Dracula",
        colors: {
            primary: "#BD93F9",
            planMode: "#FF79C6",
            selection: "#6272A4",
            thinking: "#FF79C6",
            success: "#50FA7B",
            error: "#FF5555",
            info: "#8BE9FD",
            background: "#282A36",
            surface: "#343746",
            dialogSurface: "#21222C",
            thinkingBorder: "#6272A4",
            dimSeparator: "#44475A",
        },
    },
    {
        name: "Monokai Pro",
        colors: {
            primary: "#FFD866",
            planMode: "#AB9DF2",
            selection: "#AB9DF2",
            thinking: "#AB9DF2",
            success: "#A9DC76",
            error: "#FF6188",
            info: "#78DCE8",
            background: "#2D2A2E",
            surface: "#403E41",
            dialogSurface: "#221F22",
            thinkingBorder: "#5B595C",
            dimSeparator: "#727072",
        },
    },
    {
        name: "Tokyo Night",
        colors: {
            primary: "#7AA2F7",
            planMode: "#BB9AF7",
            selection: "#7AA2F7",
            thinking: "#BB9AF7",
            success: "#9ECE6A",
            error: "#F7768E",
            info: "#7DCFFF",
            background: "#1A1B26",
            surface: "#24283B",
            dialogSurface: "#16161E",
            thinkingBorder: "#3B4261",
            dimSeparator: "#565F89",
        },
    },
    {
        name: "Nord",
        colors: {
            primary: "#EBCB8B",
            planMode: "#B48EAD",
            selection: "#81A1C1",
            thinking: "#B48EAD",
            success: "#A3BE8C",
            error: "#BF616A",
            info: "#88C0D0",
            background: "#2E3440",
            surface: "#3B4252",
            dialogSurface: "#272C36",
            thinkingBorder: "#4C566A",
            dimSeparator: "#616E88",
        },
    },
    {
        name: "Synthwave",
        colors: {
            primary: "#F472B6",
            planMode: "#A855F7",
            selection: "#E879F9",
            thinking: "#A855F7",
            success: "#4ADE80",
            error: "#EF4444",
            info: "#C084FC",
            background: "#0A0A0A",
            surface: "#171717",
            dialogSurface: "#0D0D0D",
            thinkingBorder: "#404040",
            dimSeparator: "#525252",
        },
    },
    {
        name: "Midnight Sky",
        colors: {
            primary: "#6AAEF5",
            planMode: "#B07AE8",
            selection: "#8CC4F0",
            thinking: "#B07AE8",
            success: "#58CEA0",
            error: "#E8555A",
            info: "#7DCFFF",
            background: "#0A0E14",
            surface: "#141A22",
            dialogSurface: "#0E1319",
            thinkingBorder: "#4A5A6E",
            dimSeparator: "#607080",
        },
    },
    {
        name: "Neon Nights",
        colors: {
            primary: "#E86ACA",
            planMode: "#5ED4E8",
            selection: "#D48EE0",
            thinking: "#5ED4E8",
            success: "#4ED89C",
            error: "#F04858",
            info: "#E86ACA",
            background: "#0C0814",
            surface: "#18122A",
            dialogSurface: "#110C1E",
            thinkingBorder: "#5C4878",
            dimSeparator: "#745E90",
        },
    },
    {
        name: "Hacker Terminal",
        colors: {
            primary: "#00E5A0",
            planMode: "#D946EF",
            selection: "#2DD4BF",
            thinking: "#D946EF",
            success: "#4ADE80",
            error: "#F43F5E",
            info: "#06B6D4",
            background: "#050505",
            surface: "#131313",
            dialogSurface: "#0A0A0A",
            thinkingBorder: "#2E2E2E",
            dimSeparator: "#454545",
        },
    },
    {
        name: "One Dark",
        colors: {
            primary: "#CBAACB",
            planMode: "#55B6C2",
            selection: "#98C379",
            thinking: "#55B6C2",
            success: "#98C379",
            error: "#E06C75",
            info: "#61AFEF",
            background: "#1E2127",
            surface: "#282C34",
            dialogSurface: "#191C21",
            thinkingBorder: "#3E4451",
            dimSeparator: "#5C6370",
        },
    },
    {
        name: "Xcode Midnight",
        colors: {
            primary: "#FF7AB2",
            planMode: "#6BDFFF",
            selection: "#ACF2E4",
            thinking: "#6BDFFF",
            success: "#83C9BC",
            error: "#FF6961",
            info: "#B281EB",
            background: "#1F1F24",
            surface: "#2A2A30",
            dialogSurface: "#18181D",
            thinkingBorder: "#3E3E45",
            dimSeparator: "#57575F",
        },
    },
    {
        name: "Catppuccin Frappe",
        colors: {
            primary: "#8CAAEE",
            planMode: "#CA9EE6",
            selection: "#A6D189",
            thinking: "#CA9EE6",
            success: "#A6D189",
            error: "#E78284",
            info: "#85C1DC",
            background: "#232634",
            surface: "#303446",
            dialogSurface: "#1E2030",
            thinkingBorder: "#51576D",
            dimSeparator: "#626880",
        },
    },
    {
        name: "Vercel Dark",
        colors: {
            primary: "#8B5CF6",
            planMode: "#EC4899",
            selection: "#6366F1",
            thinking: "#EC4899",
            success: "#10B981",
            error: "#EF4444",
            info: "#3B82F6",
            background: "#030712",
            surface: "#111827",
            dialogSurface: "#060C18",
            thinkingBorder: "#1F2937",
            dimSeparator: "#374151",
        },
    },
    {
        name: "Material Ocean",
        colors: {
            primary: "#82AAFF",
            planMode: "#C792EA",
            selection: "#717CB4",
            thinking: "#C792EA",
            success: "#C3E88D",
            error: "#FF5370",
            info: "#89DDFF",
            background: "#0F111A",
            surface: "#1A1C2A",
            dialogSurface: "#090B16",
            thinkingBorder: "#3B3F5C",
            dimSeparator: "#4B5178",
        },
    },
    {
        name: "Dusk",
        colors: {
            primary: "#C9A0DC",
            planMode: "#F2B866",
            selection: "#E8889A",
            thinking: "#F2B866",
            success: "#7ED4A6",
            error: "#E25A6E",
            info: "#C9A0DC",
            background: "#110D16",
            surface: "#1E1726",
            dialogSurface: "#15101C",
            thinkingBorder: "#6B5880",
            dimSeparator: "#7E6E94",
        },
    },
    {
        name: "Ocean",
        colors: {
            primary: "#3B9ECF",
            planMode: "#E0A846",
            selection: "#6CC9A1",
            thinking: "#E0A846",
            success: "#A8D45F",
            error: "#D94F4F",
            info: "#3B9ECF",
            background: "#0B1218",
            surface: "#152028",
            dialogSurface: "#0F181F",
            thinkingBorder: "#4A6A7A",
            dimSeparator: "#5E7888",
        },
    },
    {
        name: "Soft Midnight",
        colors: {
            primary: "#60A5FA",
            planMode: "#F9A8D4",
            selection: "#93C5FD",
            thinking: "#F9A8D4",
            success: "#6EE7B7",
            error: "#FCA5A5",
            info: "#67E8F9",
            background: "#0F172A",
            surface: "#1E293B",
            dialogSurface: "#0C1322",
            thinkingBorder: "#334155",
            dimSeparator: "#475569",
        },
    },
    {
        name: "Minimal Dark",
        colors: {
            primary: "#A78BFA",
            planMode: "#38BDF8",
            selection: "#818CF8",
            thinking: "#38BDF8",
            success: "#34D399",
            error: "#FB7185",
            info: "#22D3EE",
            background: "#09090B",
            surface: "#18181B",
            dialogSurface: "#0C0C0F",
            thinkingBorder: "#3F3F46",
            dimSeparator: "#52525B",
        },
    },
    {
        name: "Solarized Dark",
        colors: {
            primary: "#268BD2",
            planMode: "#6C71C4",
            selection: "#6BC0CC",
            thinking: "#6C71C4",
            success: "#859900",
            error: "#DC322F",
            info: "#2AA198",
            background: "#002B36",
            surface: "#073642",
            dialogSurface: "#00212B",
            thinkingBorder: "#586E75",
            dimSeparator: "#657B83",
        },
    },
    {
        name: "Gruvbox Dark",
        colors: {
            primary: "#FABD2F",
            planMode: "#D3869B",
            selection: "#FABD2F",
            thinking: "#D3869B",
            success: "#B8BB26",
            error: "#FB4934",
            info: "#83A598",
            background: "#282828",
            surface: "#3C3836",
            dialogSurface: "#1D2021",
            thinkingBorder: "#504945",
            dimSeparator: "#665C54",
        },
    },
    {
        name: "Rosé Pine",
        colors: {
            primary: "#EBBCBA",
            planMode: "#C4A7E7",
            selection: "#C4A7E7",
            thinking: "#C4A7E7",
            success: "#31748F",
            error: "#EB6F92",
            info: "#9CCFD8",
            background: "#191724",
            surface: "#1F1D2E",
            dialogSurface: "#16141F",
            thinkingBorder: "#26233A",
            dimSeparator: "#524F67",
        },
    },
    {
        name: "Rosé Pine Moon",
        colors: {
            primary: "#EA9A97",
            planMode: "#C4A7E7",
            selection: "#EA9A97",
            thinking: "#C4A7E7",
            success: "#3E8FB0",
            error: "#EB6F92",
            info: "#9CCFD8",
            background: "#232136",
            surface: "#2A273F",
            dialogSurface: "#1E1C31",
            thinkingBorder: "#393552",
            dimSeparator: "#56526E",
        },
    },
    {
        name: "Kanagawa",
        colors: {
            primary: "#DCD7BA",
            planMode: "#957FB8",
            selection: "#7E9CD8",
            thinking: "#957FB8",
            success: "#76946A",
            error: "#C34043",
            info: "#7E9CD8",
            background: "#1F1F28",
            surface: "#2A2A37",
            dialogSurface: "#16161D",
            thinkingBorder: "#54546D",
            dimSeparator: "#727169",
        },
    },
    {
        name: "Everforest Dark",
        colors: {
            primary: "#A7C080",
            planMode: "#D699B6",
            selection: "#A7C080",
            thinking: "#D699B6",
            success: "#83C092",
            error: "#E67E80",
            info: "#7FBBB3",
            background: "#2D353B",
            surface: "#343F44",
            dialogSurface: "#272E33",
            thinkingBorder: "#4F585E",
            dimSeparator: "#859289",
        },
    },
    {
        name: "Ayu Dark",
        colors: {
            primary: "#E6B450",
            planMode: "#D2A6FF",
            selection: "#73B8FF",
            thinking: "#D2A6FF",
            success: "#7FD962",
            error: "#D95757",
            info: "#59C2FF",
            background: "#0B0E14",
            surface: "#11151C",
            dialogSurface: "#080A0F",
            thinkingBorder: "#2D3640",
            dimSeparator: "#475266",
        },
    },
    {
        name: "GitHub Dark",
        colors: {
            primary: "#79C0FF",
            planMode: "#D2A8FF",
            selection: "#79C0FF",
            thinking: "#D2A8FF",
            success: "#56D364",
            error: "#F85149",
            info: "#58A6FF",
            background: "#0D1117",
            surface: "#161B22",
            dialogSurface: "#090D13",
            thinkingBorder: "#30363D",
            dimSeparator: "#484F58",
        },
    },
    {
        name: "Palenight",
        colors: {
            primary: "#82AAFF",
            planMode: "#C792EA",
            selection: "#82AAFF",
            thinking: "#C792EA",
            success: "#C3E88D",
            error: "#FF5370",
            info: "#89DDFF",
            background: "#292D3E",
            surface: "#343850",
            dialogSurface: "#232738",
            thinkingBorder: "#4E5272",
            dimSeparator: "#676E95",
        },
    },
    {
        name: "Vesper",
        colors: {
            primary: "#FFC799",
            planMode: "#A78BFA",
            selection: "#FFC799",
            thinking: "#A78BFA",
            success: "#6EE7B7",
            error: "#EF4444",
            info: "#FFC799",
            background: "#101010",
            surface: "#1C1C1C",
            dialogSurface: "#0C0C0C",
            thinkingBorder: "#333333",
            dimSeparator: "#505050",
        },
    },
    {
        name: "Poimandres",
        colors: {
            primary: "#ADD7FF",
            planMode: "#A6ACCD",
            selection: "#ADD7FF",
            thinking: "#A6ACCD",
            success: "#5DE4C7",
            error: "#D0679D",
            info: "#89DDFF",
            background: "#1B1E28",
            surface: "#252B37",
            dialogSurface: "#161922",
            thinkingBorder: "#3B4058",
            dimSeparator: "#506477",
        },
    },
    {
        name: "Moonlight",
        colors: {
            primary: "#82AAFF",
            planMode: "#C099FF",
            selection: "#C099FF",
            thinking: "#C099FF",
            success: "#C3E88D",
            error: "#FF757F",
            info: "#77E0C6",
            background: "#1E2030",
            surface: "#2B2F44",
            dialogSurface: "#191B28",
            thinkingBorder: "#3E4265",
            dimSeparator: "#5B5E7A",
        },
    },
    {
        name: "Vitesse Dark",
        colors: {
            primary: "#4FC1FF",
            planMode: "#C186E0",
            selection: "#4FC1FF",
            thinking: "#C186E0",
            success: "#80C97F",
            error: "#E45649",
            info: "#4FC1FF",
            background: "#121212",
            surface: "#1E1E1E",
            dialogSurface: "#0E0E0E",
            thinkingBorder: "#333333",
            dimSeparator: "#555555",
        },
    },
    {
        name: "GitHub Light",
        colors: {
            primary: "#0969DA",
            planMode: "#8250DF",
            selection: "#DDF4FF",
            thinking: "#8250DF",
            success: "#1A7F37",
            error: "#CF222E",
            info: "#0969DA",
            background: "#F6F8FA",
            surface: "#FFFFFF",
            dialogSurface: "#F3F4F6",
            thinkingBorder: "#D0D7DE",
            dimSeparator: "#8C959F",
        },
    },
    {
        name: "Solarized Light",
        colors: {
            primary: "#268BD2",
            planMode: "#6C71C4",
            selection: "#DCE8F2",
            thinking: "#6C71C4",
            success: "#859900",
            error: "#DC322F",
            info: "#2AA198",
            background: "#FDF6E3",
            surface: "#EEE8D5",
            dialogSurface: "#F7F0DE",
            thinkingBorder: "#C9C1AE",
            dimSeparator: "#93A1A1",
        },
    },
    {
        name: "Nord Light",
        colors: {
            primary: "#5E81AC",
            planMode: "#B48EAD",
            selection: "#D8DEE9",
            thinking: "#B48EAD",
            success: "#A3BE8C",
            error: "#BF616A",
            info: "#88C0D0",
            background: "#ECEFF4",
            surface: "#E5E9F0",
            dialogSurface: "#F5F7FA",
            thinkingBorder: "#D8DEE9",
            dimSeparator: "#81A1C1",
        },
    },
    {
        name: "Catppuccin Latte",
        colors: {
            primary: "#1E66F5",
            planMode: "#8839EF",
            selection: "#CCD0DA",
            thinking: "#8839EF",
            success: "#40A02B",
            error: "#D20F39",
            info: "#04A5E5",
            background: "#EFF1F5",
            surface: "#E6E9EF",
            dialogSurface: "#FFFFFF",
            thinkingBorder: "#BCC0CC",
            dimSeparator: "#9CA0B0",
        },
    },
    {
        name: "Tokyo Day",
        colors: {
            primary: "#2E7DE9",
            planMode: "#9854F1",
            selection: "#D5D6DB",
            thinking: "#9854F1",
            success: "#587539",
            error: "#F52A65",
            info: "#0F4B6E",
            background: "#D5D6DB",
            surface: "#CBCCD1",
            dialogSurface: "#E1E2E7",
            thinkingBorder: "#A1A6C5",
            dimSeparator: "#848CB5",
            selectionForeground: "#1A1B26",
        },
    },
    {
        name: "Paper Ink",
        colors: {
            primary: "#0F766E",
            planMode: "#7C3AED",
            selection: "#CFE8E2",
            thinking: "#7C3AED",
            success: "#15803D",
            error: "#B91C1C",
            info: "#0369A1",
            background: "#F5F1E8",
            surface: "#FFFCF5",
            dialogSurface: "#EFE8DA",
            thinkingBorder: "#D7CCB8",
            dimSeparator: "#8A7F70",
        },
    },
    {
        name: "Rosé Pine Dawn",
        colors: {
            primary: "#56949F",
            planMode: "#907AA9",
            selection: "#E5D9E8",
            thinking: "#907AA9",
            success: "#286983",
            error: "#B4637A",
            info: "#56949F",
            background: "#FAF4ED",
            surface: "#FFF8F0",
            dialogSurface: "#F2E9E1",
            thinkingBorder: "#DFD6CF",
            dimSeparator: "#9893A5",
        },
    },
    {
        name: "Claude",
        colors: {
            primary: "#D97757",
            planMode: "#8B5CF6",
            selection: "#F2D6C8",
            thinking: "#8B5CF6",
            success: "#2F855A",
            error: "#C53030",
            info: "#C26A4A",
            background: "#F7F1E8",
            surface: "#FFF9F2",
            dialogSurface: "#F1E7DA",
            thinkingBorder: "#DECDBA",
            dimSeparator: "#A08F80",
        },
    },
    {
        name: "ChatGPT",
        colors: {
            primary: "#10A37F",
            planMode: "#2563EB",
            selection: "#CDEEE6",
            thinking: "#2563EB",
            success: "#059669",
            error: "#DC2626",
            info: "#0F766E",
            background: "#EEF7F4",
            surface: "#FFFFFF",
            dialogSurface: "#E3F1EC",
            thinkingBorder: "#B7D8CD",
            dimSeparator: "#6B8F86",
        },
    },
    {
        name: "Gemini",
        colors: {
            primary: "#4F46E5",
            planMode: "#0EA5E9",
            selection: "#DDE7FF",
            thinking: "#0EA5E9",
            success: "#16A34A",
            error: "#E11D48",
            info: "#7C3AED",
            background: "#F5F7FF",
            surface: "#FFFFFF",
            dialogSurface: "#E9EDFF",
            thinkingBorder: "#CAD3F5",
            dimSeparator: "#7A84B8",
        },
    },
    {
        name: "Claude Dark",
        colors: {
            primary: "#E08A67",
            planMode: "#A78BFA",
            selection: "#5A4038",
            thinking: "#A78BFA",
            success: "#4ADE80",
            error: "#F87171",
            info: "#F4A261",
            background: "#171310",
            surface: "#231C18",
            dialogSurface: "#120E0C",
            thinkingBorder: "#4B3D35",
            dimSeparator: "#8D786A",
        },
    },
    {
        name: "ChatGPT Dark",
        colors: {
            primary: "#10A37F",
            planMode: "#60A5FA",
            selection: "#0F3E35",
            thinking: "#60A5FA",
            success: "#34D399",
            error: "#F87171",
            info: "#2DD4BF",
            background: "#0F1412",
            surface: "#17201C",
            dialogSurface: "#0B100E",
            thinkingBorder: "#26433B",
            dimSeparator: "#6F8E84",
        },
    },
    {
        name: "Gemini Dark",
        colors: {
            primary: "#7C83FF",
            planMode: "#38BDF8",
            selection: "#24305F",
            thinking: "#38BDF8",
            success: "#4ADE80",
            error: "#FB7185",
            info: "#A78BFA",
            background: "#0E1220",
            surface: "#171D32",
            dialogSurface: "#0A0E19",
            thinkingBorder: "#36406E",
            dimSeparator: "#7C86B6",
        },
    },
];

export const THEMES: Theme[] = RAW_THEMES.map(createTheme);

export const DEFAULT_THEME = THEMES.find((t) => t.name === "Nightfox")!;